global:
  scrape_interval:     15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'nest'
    scrape_interval: 60s
    metrics_path: /
    static_configs:
      - targets: ['nas:8000']
  
  - job_name: 'grafana'
    static_configs:
      - targets: ['nas:3000']
      